CREATE TABLE DEPARTMENT
(DEPT_ID NUMBER PRIMARY KEY,
DEPT_NAME VARCHAR2(30),
DEPT_EXAM VARCHAR2(20));

insert into DEPARTMENT values (1,'defense','gate');
insert into DEPARTMENT values (2,'external affairs','UPSC');
insert into DEPARTMENT values (3,'railways','RRB');
insert into DEPARTMENT values (4,'food security','FSO');
insert into DEPARTMENT values (5,'archealogy','SSC');

CREATE TABLE BRANCHES 
(BR_ID DECIMAL(10,2) PRIMARY KEY,
DEPT_ID NUMBER,
LOCATION VARCHAR2(30),
FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID));

insert into BRANCHES values(1.1,1,'chandigarh');
 insert into BRANCHES values(1.2,1,'delhi');
 insert into BRANCHES values(2.1,2,'delhi');
 insert into BRANCHES values(3.1,3,'noida');
 insert into BRANCHES VALUES(3.2,3,'tamil nadu');
 insert into BRANCHES values(4.1,4,'mumbai');
 insert into BRANCHES values(4.2,4,'chandigarh');
 insert into BRANCHES values(5.1,5,'hyderabad');


CREATE TABLE STUDENT_INFO 
(STU_ID NUMBER PRIMARY KEY,
STU_NAME VARCHAR2(30),
AGE NUMBER,
CONTACT NUMBER,
CITY VARCHAR2(30),
STATE VARCHAR(50),
REGION VARCHAR2(20),
EDATE DATE,
CHECK (REGION IN ('north','south')));

DECLARE 
V_STU_ID STUDENT_INFO.STU_ID%TYPE:=10;
V_STU_NAME STUDENT_INFO.STU_NAME%TYPE:= :STU_NAME;
V_AGE STUDENT_INFO.AGE%TYPE:= :AGE;
V_CONTACT STUDENT_INFO.CONTACT%TYPE := :CONTACT;
V_CITY STUDENT_INFO.CITY%TYPE:= :CITY;
V_STATE STUDENT_INFO.STATE%TYPE:= :STATE;
V_REGION STUDENT_INFO.REGION%TYPE:= :REGION;
V_EDATE STUDENT_INFO.EDATE%TYPE:= SYSDATE;   
V_EID NUMBER :=501;
V_RN VARCHAR2(20):='DELHI';
V_RS VARCHAR2(20):= 'CHENNAI';
BEGIN 
	IF V_EDATE< DATE '2025-10-30' THEN 
	INSERT INTO STUDENT_INFO (stu_id, stu_name, age, contact, city, state, region, edate)
    VALUES (v_stu_id, v_stu_name, v_age, v_contact, v_city, v_state, v_region, v_edate);
v_stu_id:=v_stu_id+1;
ELSE 
DBMS_OUTPUT.PUT_LINE('DATE PASSED');
END IF ;
END;


INSERT INTO STUDENT_INFO 
(STU_ID, STU_NAME, AGE, CONTACT, CITY, STATE, REGION, EDATE) 
VALUES (1, 'Aman Sharma', 20, 9876543210, 'Chandigarh', 'Punjab', 'north', TO_DATE('2025-01-10','YYYY-MM-DD'));

INSERT INTO STUDENT_INFO 
(STU_ID, STU_NAME, AGE, CONTACT, CITY, STATE, REGION, EDATE) 
VALUES (2, 'Priya Verma', 22, 9898989898, 'Bengaluru', 'Karnataka', 'south', TO_DATE('2025-02-14','YYYY-MM-DD'));

INSERT INTO STUDENT_INFO 
(STU_ID, STU_NAME, AGE, CONTACT, CITY, STATE, REGION, EDATE) 
VALUES (3, 'Rohit Singh', 21, 9123456789, 'Lucknow', 'Uttar Pradesh', 'north', TO_DATE('2025-03-05','YYYY-MM-DD'));

INSERT INTO STUDENT_INFO 
(STU_ID, STU_NAME, AGE, CONTACT, CITY, STATE, REGION, EDATE) 
VALUES (4, 'Kavya Nair', 23, 9012345678, 'Kochi', 'Kerala', 'south', TO_DATE('2025-04-18','YYYY-MM-DD'));

INSERT INTO STUDENT_INFO 
(STU_ID, STU_NAME, AGE, CONTACT, CITY, STATE, REGION, EDATE) 
VALUES (5, 'Arjun Mehta', 20, 9876501234, 'Delhi', 'Delhi', 'north', TO_DATE('2025-05-12','YYYY-MM-DD'));

INSERT INTO STUDENT_INFO 
(STU_ID, STU_NAME, AGE, CONTACT, CITY, STATE, REGION, EDATE) 
VALUES (6, 'Sneha Reddy', 22, 9345678901, 'Hyderabad', 'Telangana', 'south', TO_DATE('2025-06-20','YYYY-MM-DD'));

INSERT INTO STUDENT_INFO 
(STU_ID, STU_NAME, AGE, CONTACT, CITY, STATE, REGION, EDATE) 
VALUES (7, 'Harpreet Kaur', 21, 9567890123, 'Amritsar', 'Punjab', 'north', TO_DATE('2025-07-15','YYYY-MM-DD'));

INSERT INTO STUDENT_INFO 
(STU_ID, STU_NAME, AGE, CONTACT, CITY, STATE, REGION, EDATE) 
VALUES (8, 'Vikram Rao', 24, 9765432109, 'Chennai', 'Tamil Nadu', 'south', TO_DATE('2025-08-25','YYYY-MM-DD'));

SELECT * FROM student_info;

CREATE TABLE ENROLLED 
(EID NUMBER PRIMARY KEY,
STU_ID NUMBER,
DEPT_ID NUMBER,
CENTER VARCHAR2(30),
EXAM_DATE DATE,
FOREIGN KEY (STU_ID) REFERENCES STUDENT_INFO(STU_ID),
FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID));

CREATE TABLE RESULTS (EID NUMBER PRIMARY KEY, 
MARKS NUMBER,
FOREIGN KEY(EID) REFERENCES ENROLLED(EID));

INSERT INTO RESULTS (EID, MARKS) VALUES (501, 85);
INSERT INTO RESULTS (EID, MARKS) VALUES (502, 72);
INSERT INTO RESULTS (EID, MARKS) VALUES (503, 90);
INSERT INTO RESULTS (EID, MARKS) VALUES (504, 66);
INSERT INTO RESULTS (EID, MARKS) VALUES (505, 78);
INSERT INTO RESULTS (EID, MARKS) VALUES (506, 92);
INSERT INTO RESULTS (EID, MARKS) VALUES (507, 81);
INSERT INTO RESULTS (EID, MARKS) VALUES (508, 69);
INSERT INTO RESULTS (EID, MARKS) VALUES (509, 100);



CREATE TABLE EMPLOYEES (
    EMP_ID NUMBER PRIMARY KEY,
    EID NUMBER,
    DEPT_ID NUMBER,
    SALARY NUMBER(10, 2),
    JOINING_DATE DATE,
    FOREIGN KEY (EID) REFERENCES ENROLLED(EID),
    FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID)
);

