CREATE TABLE DEPARTMENT
(DEPT_ID NUMBER PRIMARY KEY,
DEPT_NAME VARCHAR2(30),
DEPT_EXAM VARCHAR2(20));

insert into DEPARTMENT values (1,'defense','gate');
insert into DEPARTMENT values (2,'external affairs','UPSC');
insert into DEPARTMENT values (3,'railways','RRB');
insert into DEPARTMENT values (4,'food security','FSO');
insert into DEPARTMENT values (5,'archealogy','SSC');

CREATE TABLE BRANCHES 
(BR_ID DECIMAL(10,2) PRIMARY KEY,
DEPT_ID NUMBER,
LOCATION VARCHAR2(30),
FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID));

insert into BRANCHES values(1.1,1,'chandigarh');
 insert into BRANCHES values(1.2,1,'delhi');
 insert into BRANCHES values(2.1,2,'delhi');
 insert into BRANCHES values(3.1,3,'noida');
 insert into BRANCHES VALUES(3.2,3,'tamil nadu');
 insert into BRANCHES values(4.1,4,'mumbai');
 insert into BRANCHES values(4.2,4,'chandigarh');
 insert into BRANCHES values(5.1,5,'hyderabad');

CREATE TABLE STATES (ST_ID NUMBER PRIMARY KEY,
SNAME VARCHAR2(50),
REGION VARCHAR2(30),
CHECK (REGION IN ('north','south')));

INSERT INTO STATES VALUES (1,  'Jammu and Kashmir', 'north');
INSERT INTO STATES VALUES (2,  'Himachal Pradesh', 'north');
INSERT INTO STATES VALUES (3,  'Punjab', 'north');
INSERT INTO STATES VALUES (4,  'Haryana', 'north');
INSERT INTO STATES VALUES (5,  'Delhi', 'north');
INSERT INTO STATES VALUES (6,  'Uttarakhand', 'north');
INSERT INTO STATES VALUES (7,  'Uttar Pradesh', 'north');
INSERT INTO STATES VALUES (8,  'Rajasthan', 'north');
INSERT INTO STATES VALUES (9,  'Madhya Pradesh', 'north');
INSERT INTO STATES VALUES (10, 'Chhattisgarh', 'north');
INSERT INTO STATES VALUES (11, 'Bihar', 'north');
INSERT INTO STATES VALUES (12, 'Jharkhand', 'north');
INSERT INTO STATES VALUES (13, 'Odisha', 'north');
INSERT INTO STATES VALUES (14, 'West Bengal', 'north');
INSERT INTO STATES VALUES (15, 'Assam', 'north');
INSERT INTO STATES VALUES (16, 'Arunachal Pradesh', 'north');
INSERT INTO STATES VALUES (17, 'Meghalaya', 'north');
INSERT INTO STATES VALUES (18, 'Manipur', 'north');
INSERT INTO STATES VALUES (19, 'Mizoram', 'north');
INSERT INTO STATES VALUES (20, 'Nagaland', 'north');
INSERT INTO STATES VALUES (21, 'Tripura', 'north');
INSERT INTO STATES VALUES (22, 'Sikkim', 'north');
INSERT INTO STATES VALUES (23, 'Maharashtra', 'north');
INSERT INTO STATES VALUES (24, 'Gujarat', 'north');
INSERT INTO STATES VALUES (25, 'Goa', 'south');  
INSERT INTO STATES VALUES (26, 'Tamil Nadu', 'south');
INSERT INTO STATES VALUES (27, 'Kerala', 'south');
INSERT INTO STATES VALUES (28, 'Karnataka', 'south');
INSERT INTO STATES VALUES (29, 'Andhra Pradesh', 'south');
INSERT INTO STATES VALUES (30, 'Telangana', 'south');


CREATE TABLE STUDENT_INFO 
(STU_ID NUMBER PRIMARY KEY,
STU_NAME VARCHAR2(30),
AGE NUMBER,
CONTACT NUMBER,
CITY VARCHAR2(30),
STATE VARCHAR(50),
REGION VARCHAR2(20),
EDATE DATE,
CHECK (REGION IN ('north','south')));

DECLARE 
V_STU_ID STUDENT_INFO.STU_ID%TYPE:=1;
V_STU_NAME STUDENT_INFO.STU_NAME%TYPE:= :STU_NAME;
V_AGE STUDENT_INFO.AGE%TYPE:= :AGE;
V_CONTACT STUDENT_INFO.CONTACT%TYPE := :CONTACT;
V_CITY STUDENT_INFO.CITY%TYPE:= :CITY;
V_STATE STUDENT_INFO.STATE%TYPE:= :STATE;
V_REGION STUDENT_INFO.REGION%TYPE:= :REGION;
V_EDATE STUDENT_INFO.EDATE%TYPE:= SYSDATE;   
V_EID NUMBER :=501;
V_RN VARCHAR2(20):='DELHI';
V_RS VARCHAR2(20):= 'CHENNAI';
BEGIN 
	IF V_EDATE< DATE '2025-10-30' THEN 
	INSERT INTO STUDENT_INFO (stu_id, stu_name, age, contact, city, state, region, edate)
    VALUES (v_stu_id, v_stu_name, v_age, v_contact, v_city, v_state, v_region, v_edate);
ELSE 
DBMS_OUTPUT.PUT_LINE('DATE PASSED');
END IF ;
END;

SELECT * FROM STUDENT_INFO;
SELECT * FROM ENROLLED;
DROP TABLE ENROLLED CASCADE CONSTRAINTS;

CREATE TABLE ENROLLED 
(EID NUMBER PRIMARY KEY,
STU_ID NUMBER,
DEPT_ID NUMBER,
CENTER VARCHAR2(30),
EXAM_DATE DATE,
FOREIGN KEY (STU_ID) REFERENCES STUDENT_INFO(STU_ID),
FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID));

CREATE TABLE RESULTS (EID NUMBER PRIMARY KEY, 
MARKS NUMBER,
FOREIGN KEY(EID) REFERENCES ENROLLED(EID));
INSERT INTO RESULTS VALUES (501,500);

CREATE TABLE EMPLOYEES (EMP_ID NUMBER PRIMARY KEY,
EID NUMBER,
DEPT_ID NUMBER,
FOREIGN KEY (EID) REFERENCES ENROLLED(EID),
FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID));
DELETE FROM ENROLLED WHERE EID=501;