CREATE TABLE DEPARTMENT
(DEPT_ID NUMBER PRIMARY KEY,
DEPT_NAME VARCHAR2(30),
DEPT_EXAM VARCHAR2(20));

insert into DEPARTMENT values (1,'defense','gate');
insert into DEPARTMENT values (2,'external affairs','UPSC');
insert into DEPARTMENT values (3,'railways','RRB');
insert into DEPARTMENT values (4,'food security','FSO');
insert into DEPARTMENT values (5,'archealogy','SSC');

CREATE TABLE BRANCHES 
(BR_ID NUMBER PRIMARY KEY,
DEPT_ID NUMBER,
LOCATION VARCHAR2(30),
FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID));

insert into BRANCHES values(1.1,1,'chandigarh');
 insert into BRANCHES values(1.2,1,'delhi');
 insert into BRANCHES values(2.1,2,'delhi');
 insert into BRANCHES values(3.1,3,'noida');
 insert into BRANCHES VALUES(3.2,3,'tamil nadu');
 insert into BRANCHES values(4.1,4,'mumbai');
 insert into BRANCHES values(4.2,4,'chandigarh');
 insert into BRANCHES values(5.1,5,'hyderabad');

CREATE TABLE STUDENT_INFO 
(STU_ID NUMBER PRIMARY KEY,
STU_NAME VARCHAR2(30),
CONTACT NUMBER,
REGION VARCHAR2(20),
EDATE DATE,
CHECK (REGION IN ('north','south')));

INSERT INTO STUDENT_INFO VALUES (101,'neo',7789349005,'north',DATE '2025-8-30');
INSERT INTO STUDENT_INFO VALUES (102,'john',7735009005,'south',DATE '2025-8-31');
INSERT INTO STUDENT_INFO VALUES (103,'arnold',9980049005,'south',DATE '2025-9-20');
INSERT INTO STUDENT_INFO VALUES (104,'sarah',9088856783,'north',DATE '2025-7-7');
INSERT INTO STUDENT_INFO VALUES (105,'tom',9088873333,'north',DATE '2025-7-25');
INSERT INTO STUDENT_INFO VALUES (106,'sheldon',9000065473,'south',DATE '2025-7-7');
INSERT INTO STUDENT_INFO VALUES (107,'penny',9088856783,'north',DATE '2025-7-23');

CREATE TABLE ENROLLED 
(EID NUMBER PRIMARY KEY,
STU_ID NUMBER,
DEPT_ID NUMBER,
CENTER VARCHAR2(30),
FOREIGN KEY (STU_ID) REFERENCES STUDENT_INFO(STU_ID),
FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID));

DECLARE 
V_STU_ID STUDENT_INFO.STU_ID%TYPE;
V_STU_NAME STUDENT_INFO.STU_NAME%TYPE;
V_CONTACT STUDENT_INFO.CONTACT%TYPE;
V_REGION STUDENT_INFO.REGION%TYPE;
V_RS VARCHAR2(20):='HYDERABAD';
V_RN VARCHAR2(20):='DELHI';
V_EID NUMBER:=501;
V_DEPT_ID DEPARTMENT.DEPT_ID%TYPE:=5;
V_EDATE STUDENT_INFO.EDATE%TYPE;

CURSOR C_ENROLL IS 
SELECT STU_ID, STU_NAME,CONTACT, REGION,EDATE
FROM STUDENT_INFO
WHERE EDATE < DATE '2025-9-1';
BEGIN 
	OPEN C_ENROLL;
LOOP
	FETCH C_ENROLL INTO V_STU_ID, V_STU_NAME,V_CONTACT,V_REGION,V_EDATE;
EXIT WHEN C_ENROLL%NOTFOUND;
IF V_REGION='north' THEN
INSERT INTO ENROLLED(EID,STU_ID,DEPT_ID,CENTER) VALUES (V_EID,V_STU_ID,V_DEPT_ID,V_RN);
V_EID:=V_EID+1;
ELSIF V_REGION='south' THEN
INSERT INTO ENROLLED(EID,STU_ID,DEPT_ID,CENTER) VALUES (V_EID,V_STU_ID,V_DEPT_ID,V_RS);
V_EID:=V_EID+1;
ELSE
DBMS_OUTPUT.PUT_LINE ('WRONG RECORDS');
END IF;
END LOOP;
COMMIT;
END;
/

CREATE TABLE EMPLOYEES (EMP_ID NUMBER PRIMARY KEY,
EID NUMBER,
DEPT_ID NUMBER,
FOREIGN KEY (EID) REFERENCES ENROLLED(EID),
FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID));

DECLARE 
V_EID RESULTS.EID%TYPE;
V_MARKS RESULTS.MARKS%TYPE;
V_EMP_ID NUMBER:=1;
V_DEPT_ID NUMBER:=5;
V_INFO VARCHAR2(20);
CURSOR C_EMP IS
SELECT EID,MARKS FROM
RESULTS;
BEGIN
	OPEN C_EMP;
	LOOP
		FETCH C_EMP INTO V_EID,V_MARKS;
IF V_MARKS>=350 THEN
INSERT INTO EMPLOYEES VALUES (V_EMP_ID,V_EID,V_DEPT_ID);
V_EMP_ID:=V_EMP_ID+1;
V_INFO:='JOB GAINED';
ELSE
V_INFO:='JOB NOT GAINED';
END IF;
		
	END LOOP;
	CLOSE C_EMP;
	
END;










