CREATE OR REPLACE VIEW EXAMS 
AS SELECT DEPT_ID AS "EXAM NUMBER",
DEPT_EXAM ||'  FOR THE DEPARTMENT OF  '||DEPT_NAME AS "DEPARTMENT'S EXAM"
FROM DEPARTMENT;

SELECT * FROM exams;

CREATE OR REPLACE VIEW RESULT AS
SELECT S.STU_ID,S.STU_NAME,S.REGION,S.EDATE,E.EID,E.CENTER,R.MARKS
FROM STUDENT_INFO S,ENROLLED E,RESULTS R
WHERE S.STU_ID=E.STU_ID AND 
E.EID=R.EID;   

SELECT * FROM RESULT;






